name: namer_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  shared_preferences: ^2.3.2
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.5
  sign_in_with_apple: ^7.0.1
  dynamic_color: ^1.8.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/google_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  min_sdk_android: 21
  adaptive_icon_background: "assets/icon/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/icon/ic_launcher_foreground.png"
  adaptive_icon_monochrome: "assets/icon/ic_launcher_monochrome.png"
  web:
    generate: true
    image_path: "assets/icon/ic_launcher.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    icon_size: 48
    image_path: "assets/icon/ic_launcher.png"